[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "37.2.0"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "13.3.1"

[[constraint]]
  name = "github.com/gruntwork-io/terratest"
  version = "0.23.0"

[prune]
  go-tests = true
  unused-packages = true
